name: Secret Practice

on:
  push:
    branches:
      - main

jobs:
  test-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Use Secret
        run: echo "Secret is configured"
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
